### ISSUE TITLE
I can't create an account

### ISSUE THREAD

**Issue by Rix565** [SRGNation/Ciiverse#2]
When I try to create an account and I click on the button to create an account on my instance of Ciiverse, it automatically redirects me to the login page without logging in.I log in and it tells me that the account/password and invalid.Help me, everything works except that!

**Comment by SRGNation** [comment]
Hello there. Are you using 000webhost to host your instance? If so, I recommend using another hosting service or try hosting it yourself because Ciiverse in general functions terribly with 000webhost.

**Comment by Rix565** [comment]
Uh no.

**Comment by Rix565** [comment]
I host Ciiverse on my pc.
